version: "3.7"
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=6011
    volumes:
      - /home/ubuntu/qbittorrent/config:/config
      - /home/Downloads:/downloads
    ports:
      - 6081:6881
      - 6081:6881/udp
      - 6011:6011  
    restart: unless-stopped
    networks:
      - web
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.torrent.entrypoints: websecure
      traefik.http.routers.torrent.rule: 'Host(`torrent.jalbrecht.fr`)'
      traefik.http.services.torrent.loadbalancer.server.port: 6011
      traefik.http.routers.torrent.tls: true
      traefik.http.routers.torrent.tls.certresolver: lets-encrypt
      traefik.http.routers.torrent.service: torrent