version: "3.7"
services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /opt/deluge:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - web
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.deluge.entrypoints: websecure
      traefik.http.routers.deluge.rule: 'Host(`deluge.jalbrecht.fr`)'
      traefik.http.services.deluge.loadbalancer.server.port: 8112
      traefik.http.routers.deluge.tls: true
      traefik.http.routers.deluge.tls.certresolver: lets-encrypt
      traefik.http.routers.deluge.service: deluge