version: "3.8"

include:
  - registry.yml
  - csjbad.yml
  - csjbad-strapi.yml
  - redis.yml
  - deluge.yml
  - csjbad-runner.yml
  - csjbad-strapi-runner.yml
  - mariadb.yml


networks:
  web:
    external: true
    name: traefik_web
  redis:
    name: redis
    driver: bridge
  mariadb:
    name: mariadb
    driver: bridge
  strapi:
    name: strapi
    driver: bridge