version: "3.8"

include:
  - registry.yml
  - redis.yml
  - deluge.yml
  - mariadb.yml


networks:
  web:
    external: true
    name: traefik_web
  redis:
    name: redis
    driver: bridge
  mariadb:
    name: mariadb
    driver: bridge