version: "3.8"

include:
  - redis.yml
  - deluge.yml
  - mariadb.yml
  - postgresql.yml

networks:
  web:
    external: true
    name: traefik_web
  redis:
    name: redis
    driver: bridge
  mariadb:
    name: mariadb
    driver: bridge
  postgresql:
    name: postgresql
    driver: bridge
  strapi:
    name: strapi
    driver: bridge

volumes:
  cache:
    driver: local
  postgresql_data:
  mariadb_data: