version: '3.8'
services:
  postgresql:
    image: docker.io/library/postgres:17-alpine
    restart: unless-stopped
    container_name: postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U postgres"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - /data/compose/15/postgres-initdb:postgres-initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    secrets:
      - postgres-password
    networks:
      - postgresql

volumes:
  postgresql_data:


secrets:
  postgres-password:
    file: $DOCKER_SECRETS_DIR/postgresql-postgres-password.secret