version: "3.7"
services:
  registry:
    restart: always
    image: registry:2
    container_name: registry
    secrets:
      - htpasswd
    volumes:
      - registry:/var/lib/registry
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_STORAGE: s3
      REGISTRY_STORAGE_S3_ACCESSKEY: $REGISTRY_S3_ACCESS
      REGISTRY_STORAGE_S3_SECRETKEY: $REGISTRY_S3_KEY
      REGISTRY_STORAGE_S3_REGIONENDPOINT: https://s3.gra.io.cloud.ovh.net/
      REGISTRY_STORAGE_S3_BUCKET: registry-jalbrecht
      REGISTRY_STORAGE_S3_SECURE: "true"
      REGISTRY_STORAGE_S3_region: gra
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /run/secrets/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR: redis
      REGISTRY_REDIS_ADDR: redis:6379
      REGISTRY_HEALTH_STORAGEDRIVER_ENABLED: false
    networks:
      - web
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.registry.entrypoints: websecure
      traefik.http.routers.registry.rule: 'Host(`registry.jalbrecht.fr`)'
      traefik.http.services.registry.loadbalancer.server.port: 5000
      traefik.http.routers.registry.tls: true
      traefik.http.routers.registry.tls.certresolver: lets-encrypt
      traefik.http.routers.registry.service: registry

volumes:
  registry:

networks:
  web:
    external: true
    name: traefik_web

secrets:
  htpasswd:
    file: $DOCKER_SECRETS_DIR/registry-login.secret